/******************************************************************************
 *
 * Module: ULTRASONIC
 *
 * File Name: ultrasonic.c
 *
 * Description: Source file for the AVR ULTRASONIC driver
 *
 * Author: Abdelmonem Magdi
 *
 *******************************************************************************/
#include "ultrasonic.h"
#include "icu.h"
#include "gpio.h"
#include <util/delay.h>

/************************** Global Variables ***********************************/
static volatile uint16 g_timePulse = 0 ;
static volatile uint8 g_count = 0 ;
/*******************************************************************************/

/************************** Private Functions **********************************/
static void Ultrasonic_Trigger(void);
/*******************************************************************************/

/*******************************************************************************
 *Description: Initialization Ultrasonic Sensor
 *Input: Void
 *Return: Void
 *******************************************************************************/
void Ultrasonic_init(void)
{
	/* Select The required parameters for Configuring ICU Driver */
	ICU_ConfigType config = {F_CPU_8,RAISING} ;

	ICU_init(&config); /* Initialization ICU */

	ICU_setCallBack(Ultrasonic_edgeProcessing); /* Setup The ICU CallBack Function */

	/* Setup TRIGGER Pin as Output pin */
	GPIO_setupPinDirection(TRIGGER_PORT, TRRIGER_PIN, PIN_OUTPUT);
}

/*******************************************************************************
 *Description: Send the Trigger pulse to the ultrasonic.
 *Input: Void
 *Return: Void
 *******************************************************************************/
static void Ultrasonic_Trigger(void)
{
	/* Send one on TRIGGER Pin */
	GPIO_writePin(TRIGGER_PORT, TRRIGER_PIN, LOGIC_HIGH);

	_delay_us(10); /* TRIGGER Pulse = 10 us */

	/* Send zero On TRIGGER Pin After delay */
	GPIO_writePin(TRIGGER_PORT, TRRIGER_PIN, LOGIC_LOW);
}

/*******************************************************************************
 *Description: Read Distance between Sensor and object
 *Input: Void
 *Return: The measured distance in Centimeter
 *******************************************************************************/
uint16 Ultrasonic_readDistance(void)
{
	uint16 distance = 0  ;

	Ultrasonic_Trigger(); /* Send The TRIGGER Pulse */

	while(g_count != 2); /* Waiting for Wave to be sent and come back*/

	distance = 1 + g_timePulse / 58 ; /* Calculate The Distance */

	g_count = 0 ; /* Reset Tick of Timer */

	return distance;
}

/*******************************************************************************
 *Description: calculate pulse time generated by the ultrasonic sensor
 *Input: Void
 *Return: Void
 *******************************************************************************/
void Ultrasonic_edgeProcessing(void)
{
	g_count++ ;

	if(g_count == 1)
	{
		ICU_clearTimerValue() ; /* Start The Timer */
		ICU_setEdgeDetectionType(FALLING); /* Next Edge Falling */
	}
	else if(g_count == 2)
	{
		g_timePulse = ICU_getInputCaptureValue(); /* Pulse Time */
		ICU_setEdgeDetectionType(RAISING); /* Next Edge Raising */
	}
}
